run:
	chmod 777 exp1_copy.tcl
	chmod 777 exp2_copy.tcl
	chmod 777 exp3.tcl
	chmod 777 exp3_copy.tcl
	chmod 777 parser_copy.py
	chmod 777 parser_copy_exp2.py
	chmod 777 parser_exp3.py
	chmod 777 e1
	chmod 777 e2
